import { gql } from "@apollo/client";
import client from "../contentful_resources/apollo-client";

import Head from 'next/head'
import DefaultComp from '../components/default/Default'
import Hero from '../components/home-hero/Hero'

import queries from '../contentful_resources/queries';

export default function Home({homepageData}) {
  const { 
    title, 
    headerTitle, 
    headerSubTitle, 
    headerBackground 
  } = homepageData;
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <DefaultComp data={homepageData}/>

      <Hero 
        headerTitle={headerTitle} 
        headerSubTitle={headerSubTitle} 
        headerBackground={headerBackground} 
      />
      
     
    </div>
  )
}

// Server side rendering

export const getServerSideProps = async () => {
  const { data } = await client.query({
    query: gql`${queries.home}`,
  });

  return {
    props: {
      homepageData: data.homepageCollection.items[0],
    },
 };
}

// Static site generation

// export const getStaticProps = async () => {
//   const { data } = await client.query({
//     query: gql`${queries.home}`,
//   });

//   return {
//     props: {
//       homepageData: data.homepageCollection.items[0],
//     },
//  };
// }
